name: Spell Check

on:
  pull_request:
    paths:
      - "**.md"
      - "**.py"
      - "**.yml"
      - "**.yaml"
      - "**.toml"
  push:
    branches: [main]
    paths:
      - "**.md"
      - "**.py"
      - "**.yml"
      - "**.yaml"
      - "**.toml"

jobs:
  check:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@v1.29.0
        with:
          config: ./typos.toml
